name: Benchmark on Linux + Alderlake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, Linux, alderlake]
    timeout-minutes: 6
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Benchmark
      shell: bash
      working-directory: ${{github.workspace}}
      run: python3 buildbot/runCI.py -workdir ${{github.workspace}}/labs -runner LinuxIntelAlderlake

