name: Benchmark on Windows + Zen3

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, windows]
    timeout-minutes: 9
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Benchmark
      shell: powershell
      working-directory: ${{github.workspace}}
      run: python buildbot\runCI.py -workdir ${{github.workspace}}\labs -runner WinZen3

